// Lightweight odds only: independent of prediction computation. Cron every five minutes.
import {signalsCore as C,signalErrorCategory,signalFetch,signalGame,signalsEnabled,claimSignalsRun,captureSignalQuotes,settleSignalGame,missedSignalWindows} from '../sports-hub-ai/signals.ts';
const URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
async function db(path:string,init:RequestInit={}){const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok)throw new Error(`database_${r.status}`);const t=await r.text();return t?JSON.parse(t):null;}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});const now=Date.now(),id=`odds:${Math.floor(now/300000)}`,started=new Date(now).toISOString();let written=0,missed=0,last:string|null=null;const errors:string[]=[];const dueTimes:number[]=[];let claimed=false;
 try{if(!await signalsEnabled(db))return Response.json({status:'disabled'});const prior=(await db('betting_capture_runs?status=eq.ok&select=next_poll_at&order=started_at.desc&limit=1'))?.[0];if(prior?.next_poll_at&&Date.parse(prior.next_poll_at)>now)return Response.json({status:'not_due'},{status:202});if(!await claimSignalsRun(db,id))return Response.json({status:'rate_limited'},{status:202});claimed=true;await db('betting_capture_runs',{method:'POST',body:JSON.stringify({id,started_at:started,status:'running'})});
 // Expired locks are operational metadata, not price/history retention.
 await db(`betting_capture_locks?claimed_at=lt.${encodeURIComponent(new Date(now-7*864e5).toISOString())}`,{method:'DELETE'});
 const games:any[]=[];
 for(const sport of ['nfl','cfb']){
 try{
 const base='https://site.api.espn.com/apis/site/v2/sports/football/'+(sport==='cfb'?'college-football':'nfl')+'/scoreboard';
 const extra=sport==='cfb'?'&groups=80&limit=300':'';
 let data=await signalFetch(base+'?limit=300'+extra),received=new Date().toISOString();
 const parse=(d:any)=>(d.events||[]).map((ev:any)=>({...signalGame(ev,sport),observedAt:received})).filter((g:any)=>sport==='nfl'||C.top25(g));
 let slate=parse(data);
 if(slate.length&&slate.every((g:any)=>g.state==='post')&&data.week?.number&&data.season?.year){for(const g of slate){await settleSignalGame(db,g).catch(()=>errors.push('settlement_failed'));missed+=await missedSignalWindows(db,g).catch(()=>0);}data=await signalFetch(`${base}?week=${Number(data.week.number)+1}&seasontype=${data.season.type}&dates=${data.season.year}${extra}`);received=new Date().toISOString();slate=parse(data);}games.push(...slate);
 }catch(error){errors.push(signalErrorCategory(error));}
 }
 for(const g of games){try{await settleSignalGame(db,g);missed+=await missedSignalWindows(db,g);if(!C.pregame(g))continue;const latest=(await db(`betting_quote_snapshots?sport=eq.${g.sport}&event_id=eq.${encodeURIComponent(g.id)}&schedule_instance=eq.${encodeURIComponent(new Date(g.date).toISOString())}&select=observed_at&order=observed_at.desc&limit=1`))?.[0];const interval=C.intervalMinutes(g)*60000;if(latest&&Date.now()-Date.parse(latest.observed_at)<interval-15000){dueTimes.push(Date.parse(latest.observed_at)+interval);continue;}const rows=await captureSignalQuotes(db,g,id,g.observedAt);written+=rows.length;if(rows.length){last=g.observedAt;dueTimes.push(Date.parse(g.observedAt)+interval);}else dueTimes.push(Date.now()+5*60000);}catch(error){errors.push(signalErrorCategory(error));}}
 const future=games.filter((g:any)=>C.pregame(g));let nextPoll=dueTimes.length?Math.min(...dueTimes):Date.now()+60*60000;for(const g of future)for(const boundary of [1440,120]){const t=Date.parse(g.date)-boundary*60000;if(t>Date.now())nextPoll=Math.min(nextPoll,t);}const status=errors.length?(written?'partial':'error'):'ok';await db(`betting_capture_runs?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({finished_at:new Date().toISOString(),status,written,missed,last_observed_at:last,next_poll_at:new Date(nextPoll).toISOString(),error_category:errors[0]||null})});return Response.json({status,written,missed});
 }catch(error){const category=signalErrorCategory(error);if(claimed)await db(`betting_capture_runs?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({finished_at:new Date().toISOString(),status:'error',written,missed,last_observed_at:last,error_category:category})}).catch(()=>{});return Response.json({status:'error',error_category:category},{status:500});}});
