import '../_shared/betting-signals-core.js';
const C = (globalThis as any).SportsHubSignalsCore;
type DB = (path:string, init?:RequestInit)=>Promise<any>;
type Json = Record<string,any>;
const VERSION='signals-v2', POLICY='tminus_30_60_v1';
const SITE='https://site.api.espn.com/apis/site/v2/sports/football/nfl';
const encode=encodeURIComponent;
export const signalsCore=C;
export function signalErrorCategory(error:any){const message=String(error?.message||'');if(/^database_\d{3}$/.test(message))return message;if(['source_timeout','source_unavailable','source_invalid_json'].includes(message))return message;if(error?.name==='TimeoutError'||error?.name==='AbortError')return 'source_timeout';return 'collector_failed';}
export async function signalFetch(url:string):Promise<any>{let category='source_unavailable';for(let i=0;i<3;i++){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(url,{headers:{accept:'application/json','user-agent':'Sports-Hub/1.0'},signal:controller.signal});if(r.ok){try{return await r.json();}catch(_){throw new Error('source_invalid_json');}}if(r.status<500&&r.status!==429)throw new Error('source_unavailable');}catch(e){category=signalErrorCategory(e)==='source_timeout'?'source_timeout':signalErrorCategory(e)==='source_invalid_json'?'source_invalid_json':'source_unavailable';if(i===2)throw new Error(category);}finally{clearTimeout(timeout);}await new Promise(r=>setTimeout(r,200*(i+1)));}throw new Error(category);}

export function signalGame(ev:any){const c=ev.competitions?.[0]||{},s=c.competitors||[],st=ev.status?.type||c.status?.type||{},side=(v:string)=>{const x=s.find((a:any)=>a.homeAway===v)||{};return {id:String(x.team?.id||''),abbr:x.team?.abbreviation,score:C.number(x.score?.value??x.score)};};return {id:String(ev.id),date:ev.date,state:st.state,status:st.name||st.description||'',completed:st.completed===true,seasonType:ev.season?.type??c.season?.type,season:ev.season?.year,neutral:c.neutralSite===true,home:side('home'),away:side('away'),odds:c.odds?.[0]||null};}
export async function signalsEnabled(db:DB){return (await db('betting_signals_config?id=eq.1&select=capture_enabled'))?.[0]?.capture_enabled===true;}
export async function claimSignalsRun(db:DB,id:string){const rows=await db('betting_capture_locks?on_conflict=slot',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:JSON.stringify({slot:id})});return !!rows?.length;}
async function hash(v:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(v)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
const instance=(g:any)=>new Date(g.date).toISOString();
export async function captureSignalQuotes(db:DB,g:any,runId:string,observedAt:string){if(!C.pregame(g)||!C.pregame(g,observedAt))return [];const rawHash=await hash(g.odds);if(!C.pregame(g))return [];const rows=C.normalizeOdds(g.odds,g).filter((q:any)=>q.line!=null||[q.home_price,q.away_price,q.over_price,q.under_price].some(x=>x!=null)).map((q:any)=>({...q,sport:'nfl',event_id:g.id,schedule_instance:instance(g),scheduled_start_at:g.date,observed_at:observedAt,raw_payload_hash:rawHash,collector_version:VERSION,capture_run_id:runId}));if(!rows.length)return [];await db('betting_quote_snapshots?on_conflict=capture_run_id,sport,event_id,provider_id,market',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(rows)});return await db(`betting_quote_snapshots?capture_run_id=eq.${encode(runId)}&event_id=eq.${encode(g.id)}&select=*`);}
// Current-season schedules and season-specific standings, never model-capped rest values.
const divisionCache=new Map<number,Promise<Json>>();
async function divisions(year:number){if(!divisionCache.has(year))divisionCache.set(year,(async()=>{const data=await signalFetch(`https://site.api.espn.com/apis/v2/sports/football/nfl/standings?season=${year}&level=3`),out:Json={};const walk=(n:any,path:string[])=>{const p=[...path,String(n.name||n.abbreviation||n.id||'')];if(n.standings?.entries&&p.length>=2)for(const e of n.standings.entries)if(e.team?.id)out[String(e.team.id)]=p.join('/');for(const ch of n.children||[])walk(ch,p);};for(const ch of data.children||[])walk(ch,[]);return out;})().catch(()=>({})));return await divisionCache.get(year)!;}
async function previous(teamId:string,g:any,year:number){const d=await signalFetch(`${SITE}/teams/${teamId}/schedule?season=${year}&seasontype=2`);if(Number(d.season?.year)!==year)return null;const prev=(d.events||[]).filter((e:any)=>{const c=e.competitions?.[0]||{},type=e.seasonType?.type??e.season?.type??d.season?.type;return Number(type)===2&&c.status?.type?.completed===true&&Date.parse(e.date)<Math.min(Date.parse(g.date),Date.now());}).sort((a:any,b:any)=>Date.parse(b.date)-Date.parse(a.date))[0]?.date||null;const event=(d.events||[]).find((e:any)=>String(e.id)===String(g.id)),week=C.number(event?.week?.number),bye=C.number(d.byeWeek);return {date:prev,postBye:week!=null&&bye!=null?week===bye+1:null};}
export async function signalInputs(g:any){const year=Number(g.season)||new Date(g.date).getUTCFullYear();const [h,a,div]=await Promise.all([previous(g.home.id,g,year).catch(()=>null),previous(g.away.id,g,year).catch(()=>null),divisions(year)]);return {matchup:`${g.away.abbr||g.away.id} @ ${g.home.abbr||g.home.id}`,season:year,season_type:g.seasonType??null,neutral:g.neutral,scheduled_start_at:g.date,home_previous_game_at:h?.date||null,away_previous_game_at:a?.date||null,home_post_bye:h?.postBye??null,away_post_bye:a?.postBye??null,home_division:div[g.home.id]||null,away_division:div[g.away.id]||null,division_source:Object.keys(div).length?`espn_standings_${year}`:null,source_checked_at:new Date().toISOString(),provider_policy:'espn_primary_provider_v1'};}
export async function saveSignalDecision(db:DB,g:any,quotes:any[],inputs:any,modelContext:any){modelContext={...modelContext,inputs_hash:await hash({inputs,quotes:quotes.map(q=>q.raw_payload_hash),model:modelContext})};inputs={...inputs,provider_id:quotes[0]?.provider_id||'unknown',provider_name:quotes[0]?.provider_name||null};const now=new Date().toISOString(),evaluations=C.evaluateRules(inputs,quotes,now);if(C.pregame(g)){await db('betting_signal_current?on_conflict=sport,event_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({sport:'nfl',event_id:g.id,schedule_instance:instance(g),scheduled_start_at:g.date,observed_at:quotes[0]?.observed_at||g.observedAt||now,inputs,rule_evaluations:evaluations,model_context:modelContext,quality_flags:quotes.length?[]:['quotes_unavailable']})});}const receipt=quotes[0]?.observed_at||g.observedAt||now;if(!C.decisionWindow(g)||!C.decisionWindow(g,receipt)||quotes.some(q=>!C.decisionWindow(g,q.observed_at)))return {evaluated:0,unpriced:0};const rows=await Promise.all([...evaluations,...C.evaluateResearch(inputs,quotes,now)].map(async(e:any)=>{
 const q=quotes.find(x=>x.market===e.market);let movement:number|null=null,firstAt:string|null=null;
 if(q?.line!=null&&q.provider_id&&q.provider_id!=='unknown'){
   // Bounded as-of query. A later quote must never leak into the frozen research cohort.
   const first=(await db(`betting_quote_snapshots?sport=eq.nfl&event_id=eq.${encode(g.id)}&schedule_instance=eq.${encode(instance(g))}&source=eq.${encode(q.source)}&provider_id=eq.${encode(q.provider_id)}&market=eq.${encode(e.market)}&observed_at=lt.${encode(q.observed_at)}&line=not.is.null&select=*&order=observed_at.asc,id.asc&limit=1`).catch(()=>[]))?.[0];
   if(first&&Date.parse(first.observed_at)<Date.parse(q.observed_at)&&first.line!=null&&['sport','event_id','schedule_instance','source','provider_id','market'].every(k=>first[k]===q[k])){movement=(q.line-first.line)*(e.market==='spread'&&e.selection_side==='away'?-1:1);firstAt=first.observed_at;}
 }
 const projection=C.number(modelContext.projection?.[e.market]);
 const gap=modelContext.availability==='available'&&projection!=null&&q?.line!=null?Math.abs(e.market==='spread'?projection+q.line:projection-q.line):null;
 const frozenInputs={...e.inputs,opponent_price:e.selection_side==='home'?q?.away_price??null:e.selection_side==='away'?q?.home_price??null:null,observed_line_movement:movement,movement_first_observed_at:firstAt};
 const frozenContext={...modelContext,same_market_gap:gap,inputs_hash:await hash({inputs:frozenInputs,quote_hash:q?.raw_payload_hash||null,model:modelContext})};
 return {...e,inputs:frozenInputs,sport:'nfl',event_id:g.id,schedule_instance:instance(g),decision_policy:POLICY,decided_at:new Date().toISOString(),observed_at:q?.observed_at||quotes[0]?.observed_at||g.observedAt||now,scheduled_start_at:g.date,quote_snapshot_id:q?.id||null,engine_version:VERSION,model_context:frozenContext};
 }));if(!C.decisionWindow(g))return {evaluated:0,unpriced:0};const saved=await db('betting_system_decisions?on_conflict=sport,event_id,schedule_instance,rule_id,rule_version,decision_policy',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:JSON.stringify(rows)});return {evaluated:saved?.length||0,unpriced:saved?.filter((r:any)=>r.status==='unpriced_match').length||0};}
async function page(db:DB,path:string){const all:any[]=[];for(let offset=0;;offset+=500){const rows=await db(`${path}&limit=500&offset=${offset}`);all.push(...rows);if(rows.length<500)return all;}}
export async function settleSignalGame(db:DB,g:any){const decisions=await page(db,`betting_system_decisions?event_id=eq.${encode(g.id)}&select=*&order=id.asc`);let n=0;for(const d of decisions){const rescheduled=d.schedule_instance!==instance(g),cancelled=/cancel/i.test(g.status||'');const result=rescheduled||cancelled?'void':C.grade(d,g);if(result==='pending')continue;const old=(await db(`betting_system_settlements?decision_id=eq.${d.id}&select=*`))?.[0];if(old?.result==='void'&&['cancelled','schedule_changed'].includes(old.correction_reason))continue;const hs=g.home?.score??null,as=g.away?.score??null;if(old?.result===result&&old.final_home_score===hs&&old.final_away_score===as)continue;const reason=rescheduled?'schedule_changed':cancelled?'cancelled':old?'score_correction':null;const audit=old?[...(old.audit_trail||[]),{result:old.result,final_home_score:old.final_home_score,final_away_score:old.final_away_score,graded_at:old.graded_at,reason}]:[];await db('betting_system_settlements?on_conflict=decision_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({decision_id:d.id,result,final_home_score:hs,final_away_score:as,graded_at:new Date().toISOString(),grading_version:VERSION,correction_reason:reason,audit_trail:audit})});n++;}return n;}
export async function missedSignalWindows(db:DB,g:any){if(C.pregame(g)||Date.parse(g.date)>Date.now()||/delay|postpon|suspend|cancel/i.test(g.status||''))return 0;const rows=[...C.RULES,...C.RESEARCH].map((r:any)=>({sport:'nfl',event_id:g.id,schedule_instance:instance(g),rule_id:r.id,rule_version:r.version,decision_policy:POLICY,decided_at:new Date().toISOString(),scheduled_start_at:g.date,status:'missed_window',market:r.market,selection_side:r.side,engine_version:VERSION,quality_flags:['missed_capture_window']}));const got=await db('betting_system_decisions?on_conflict=sport,event_id,schedule_instance,rule_id,rule_version,decision_policy',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:JSON.stringify(rows)});return got?.length||0;}
export async function reconcileSignals(db:DB){
 // A week of score corrections plus genuinely unresolved experiments; never refetch every historical slate.
 const rows=await page(db,'betting_system_decisions?select=event_id,scheduled_start_at,status,betting_system_settlements(result,correction_reason)&status=in.(matched,unpriced_match)&order=id.asc');
 const now=Date.now(),eligible=rows.filter((r:any)=>{const s=Array.isArray(r.betting_system_settlements)?r.betting_system_settlements[0]:r.betting_system_settlements;return Date.parse(r.scheduled_start_at)<now&&(!s||s.result==='pending'||(s.result!=='void'&&Date.parse(r.scheduled_start_at)>now-7*864e5));});
 const dates=[...new Set(eligible.map((r:any)=>new Date(r.scheduled_start_at).toISOString().slice(0,10).replaceAll('-','')))];let graded=0;
 for(const date of dates.slice(-14)){const data=await signalFetch(`${SITE}/scoreboard?dates=${date}`);for(const ev of data.events||[])graded+=await settleSignalGame(db,signalGame(ev));}return graded;
}
