const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../supabase/functions/_shared/betting-signals-core.js');global.SportsHubSignalsCore=C;
const UI=require('../betting-signals-ui.js');
const H=import('../supabase/functions/sports-hub-ai/signals.ts');
function memory(){let n=0;const t={betting_quote_snapshots:[],betting_system_decisions:[],betting_signal_current:[],betting_system_settlements:[]};return {t,db:async(path,init={})=>{const [name,query]=path.split('?'),p=new URLSearchParams(query),rows=t[name];if(!rows)throw Error(name);if(init.method==='POST'){let body=JSON.parse(init.body);body=Array.isArray(body)?body:[body];const out=[];for(const r of body){const keys=(p.get('on_conflict')||'id').split(','),old=rows.find(x=>keys.every(k=>x[k]===r[k]));if(old){if(init.headers?.Prefer?.includes('merge-duplicates'))Object.assign(old,r);continue;}const v={id:++n,...r};rows.push(v);out.push(v);}return out;}return rows.filter(r=>[...p].every(([k,v])=>!v.startsWith('eq.')||String(r[k])===v.slice(3))).slice(+(p.get('offset')||0),+(p.get('offset')||0)+ +(p.get('limit')||500));}};}
const game=()=>({id:'same-id',sport:'cfb',season:2026,seasonType:2,state:'pre',date:new Date(Date.now()+45*60000).toISOString(),observedAt:new Date().toISOString(),neutral:false,home:{id:'1',abbr:'H',rank:5},away:{id:'2',abbr:'A',rank:null},odds:{provider:{id:'100'},spread:-7,homeTeamOdds:{moneyLine:-200,spreadOdds:-110},awayTeamOdds:{moneyLine:170,spreadOdds:-110},overUnder:51,overOdds:-110,underOdds:-110}});
const inputs=g=>({sport:'cfb',scheduled_start_at:g.date,season_type:2,home_rank:5,away_rank:null,home_conference:'ACC',away_conference:'SEC',conference_source:'espn',neutral:false});
test('two independent teams are not a same-conference matchup',()=>{const d={sport:'cfb',inputs:{home_conference:'FBS Independents',away_conference:'FBS Independents',conference_source:'espn',home_independent:true,away_independent:true}};assert.equal(C.filterResearch([d],{division:'division'}).length,0);assert.equal(C.filterResearch([d],{division:'nondivision'}).length,1);});
test('Top 25 boundaries and normalization never include ranks 0 or 26',async()=>{assert.equal(C.top25({home:{rank:25}}),true);for(const rank of [0,26,99,null])assert.equal(C.top25({home:{rank}}),false);const h=await H,g=h.signalGame({id:1,competitions:[{competitors:[{homeAway:'home',team:{id:1},curatedRank:{current:25}},{homeAway:'away',team:{id:2},curatedRank:{current:99}}]}]},'cfb');assert.equal(g.sport,'cfb');assert.equal(g.home.rank,25);assert.equal(g.away.rank,null);});
test('CFB records six sides, not NFL rules; freeze survives later rank changes',async()=>{const h=await H,m=memory(),g=game(),q=await h.captureSignalQuotes(m.db,g,'r',g.observedAt);assert.equal(q.length,3);await h.saveSignalDecision(m.db,g,q,inputs(g),{});assert.equal(m.t.betting_system_decisions.length,6);assert.ok(m.t.betting_system_decisions.every(d=>d.rule_id.startsWith('cfb_research_')&&d.inputs.home_rank===5&&d.sport==='cfb'));g.home.rank=8;await h.saveSignalDecision(m.db,g,q,inputs(g),{});assert.ok(m.t.betting_system_decisions.every(d=>d.inputs.home_rank===5));assert.deepEqual(m.t.betting_signal_current[0].rule_evaluations,[]);});
test('unranked matchup rejected; CFB settlement survives dropping out of rankings and isolates NFL',async()=>{const h=await H,m=memory(),g=game(),q=await h.captureSignalQuotes(m.db,g,'r',g.observedAt);await h.saveSignalDecision(m.db,g,q,inputs(g),{});m.t.betting_system_decisions.push({id:100,sport:'nfl',event_id:g.id});g.home.rank=null;assert.deepEqual(await h.captureSignalQuotes(m.db,g,'u',g.observedAt),[]);assert.equal((await h.saveSignalDecision(m.db,g,q,inputs(g),{})).evaluated,0);await h.settleSignalGame(m.db,{...g,state:'post',completed:true,home:{...g.home,score:28},away:{...g.away,score:21}});assert.equal(m.t.betting_system_settlements.length,6);assert.ok(m.t.betting_system_settlements.every(d=>d.decision_id!==100));});
test('conference and ranked-matchup filters use frozen CFB inputs; missing membership not guessed',()=>{const i=inputs(game()),d={sport:'cfb',inputs:i};assert.equal(C.filterResearch([d],{division:'nondivision',ranking:'mixed'}).length,1);assert.equal(C.filterResearch([{...d,inputs:{...i,away_rank:20}}],{ranking:'both'}).length,1);assert.equal(C.filterResearch([{...d,inputs:{...i,away_conference:null}}],{division:'nondivision'}).length,0);assert.equal(C.filterResearch([{...d,inputs:{...i,away_conference:'ACC'}}],{division:'division'}).length,1);});
test('CFB UI uses conference labels, entry ranks, correct sport links and no NFL fixed tests',()=>{const html=UI.systemResultsHTML({filters:{sport:'cfb',scope:'explore'},decisions:[{id:1,sport:'cfb',event_id:'x',rule_id:'cfb_research_spread_home'}]});for(const label of ['CFB Top 25','Same conference','Nonconference','Ranked vs. ranked','spread · home','data-bs-sport="cfb"'])assert.ok(html.includes(label),label);assert.doesNotMatch(html,/data-bs-scope="rules"/);assert.match(UI.signalsSummaryHTML({sport:'cfb',eventId:'x'}),/Collecting Top 25/);});
test('adapter separates league cache and filters even with shared event IDs',async()=>{const calls=[];const ctx={SportsHubSignalsCore:C,URLSearchParams,AbortController,setTimeout,clearTimeout,Date,SPORTS_HUB_SUPABASE:{url:'https://test',key:'public'},fetch:async url=>{const u=new URL(url);calls.push(u);return {ok:true,json:async()=>u.pathname.endsWith('betting_system_decisions')?[{id:'n',sport:'nfl',rule_id:'nfl_research_spread_home'},{id:'c',sport:'cfb',rule_id:'cfb_research_spread_home'}]:[]};}};vm.runInNewContext(fs.readFileSync(require.resolve('../cloud-signals.js'),'utf8'),ctx);const api=ctx.SportsHubCloudSignals,dates={from:'2026-09-01',to:'2026-10-08'};await api.loadCurrent('nfl',['same']);await api.loadCurrent('cfb',['same']);const r=await api.loadResults(null,null,dates,{sport:'cfb',scope:'explore'});assert.equal(r.decisions.length,1);assert.equal(r.decisions[0].sport,'cfb');await api.loadHistory('same','spread',null,dates,'cfb');assert.ok(calls.filter(u=>u.pathname.endsWith('betting_quote_snapshots')).some(u=>u.searchParams.get('sport')==='eq.cfb'));});
