"""Chronological ridge/logistic fitting. Train 2022-24, select 2024-25,
test once on 2025-26. Results contain no betting ROI without archived odds.
"""
import json,pathlib,subprocess,numpy as np
from scipy.optimize import minimize
from scipy.special import expit
R=pathlib.Path(__file__).resolve().parents[1]
rows=json.loads(subprocess.check_output(['node',str(R/'scripts/nba-features.js')]))
mk=['homeCourt','net','form','record','rest','b2b'];tk=['intercept','scoring','recentScoring','restTotal','b2bTotal']
train=[r for r in rows if r['season']<=2024];val=[r for r in rows if r['season']==2025];test=[r for r in rows if r['season']==2026]
def xy(rs,keys,target):return np.array([[r['f'][k] for k in keys] for r in rs]),np.array([r[target] for r in rs])
def fit(rs,keys,target,alpha):
    x,y=xy(rs,keys,target);scale=np.std(x,axis=0);scale[scale<1e-8]=1;x=x/scale;p=np.eye(x.shape[1]);p[0,0]=0
    if target=='win':
        def fun(w):
            z=x@w;return np.mean(np.logaddexp(0,z)-y*z)+alpha*np.dot(w,p@w)/(2*len(y)),x.T@(expit(z)-y)/len(y)+alpha*p@w/len(y)
        opt=minimize(fun,np.zeros(x.shape[1]),jac=True,method='BFGS',options={'gtol':1e-9});w=opt.x
    else:w=np.linalg.solve(x.T@x+alpha*p,x.T@y)
    return w/scale
def loss(rs,keys,target,w):
    x,y=xy(rs,keys,target);p=expit(x@w) if target=='win' else x@w
    return float(np.mean((p-y)**2))
config={};selected={}
for name,target,keys in [('winner','win',mk),('margin','margin',mk),('total','total',tk)]:
    candidates=[(loss(val,keys,target,fit(train,keys,target,a)),a) for a in [0,10,100,1000]]
    _,alpha=min(candidates);selected[name]=alpha;config[name]=[round(float(v),9) for v in fit(train+val,keys,target,alpha)]
x,y=xy(test,mk,'win');p=np.clip(expit(x@np.array(config['winner'])),.02,.98)
xm,ym=xy(test,mk,'margin');xt,yt=xy(test,tk,'total')
validation={'trainSeasons':[2023,2024],'selectionSeason':2025,'holdoutSeason':2026,'trainN':len(train),'selectionN':len(val),'holdoutN':len(test),
 'winnerAccuracy':float(np.mean((p>=.5)==y)),'brier':float(np.mean((p-y)**2)),
 'marginMAE':float(np.mean(abs(xm@config['margin']-ym))),'totalMAE':float(np.mean(abs(xt@config['total']-yt))),
 'homeBaselineAccuracy':float(np.mean(y)),'homeBaselineBrier':float(np.mean((np.mean([r['win'] for r in train+val])-y)**2)),
 'marginBaselineMAE':float(np.mean(abs(np.mean([r['margin'] for r in train+val])-ym))),
 'totalBaselineMAE':float(np.mean(abs(np.mean([r['total'] for r in train+val])-yt))),
 'selectedRidge':selected,'method':'Chronological: train 2022-24, select 2024-25, refit through 2024-25, untouched 2025-26 holdout','bettingROI':None}
config['validation']=validation
(R/'supabase/functions/_shared/nba-model-config.js').write_text('/* Generated by scripts/fit-nba.py. Frozen before prospective capture. */\n(function(root){const config='+json.dumps(config,separators=(',',':'))+';root.SportsHubNBAConfig=config;if(typeof module!=="undefined"&&module.exports)module.exports=config;})(globalThis);\n')
(R/'data/nba-validation.json').write_text(json.dumps(validation,indent=2)+'\n')
print(json.dumps(validation,indent=2))
